# backend/robots_generator.py - Robots.txt Generator & Validator
import re
import httpx
from datetime import datetime
from typing import Dict, List, Optional, Any
from urllib.parse import urljoin
from sqlalchemy.orm import Session

from database import SessionLocal, Website

# ─── Constants ───
DEFAULT_HEADERS = {
    "User-Agent": "SEOIntelligenceBot/1.0 (+https://example.com/bot)",
    "Accept": "text/plain,text/html,*/*",
}

# Platform-specific disallow rules
PLATFORM_RULES: Dict[str, List[Dict[str, Any]]] = {
    "shopify": [
        {"path": "/admin", "reason": "Shopify admin panel — no SEO value"},
        {"path": "/cart", "reason": "Cart pages — dynamic, duplicate content risk"},
        {"path": "/checkout", "reason": "Checkout flow — private user data"},
        {"path": "/orders", "reason": "Order pages — private user data"},
        {"path": "/account", "reason": "Customer accounts — private user data"},
        {"path": "/password", "reason": "Password entry page for protected stores"},
        {"path": "/search", "reason": "Internal search results — thin content, crawl budget waste"},
        {"path": "/collections/all", "reason": "Default 'all products' collection — often duplicate of homepage"},
        {"path": "/collections/vendors", "reason": "Vendor collections — thin/duplicate content"},
        {"path": "/blogs/news/tagged", "reason": "Tag-filtered blog pages — near-duplicate content"},
        {"path": "/pages/policies", "reason": "Policy pages — low SEO priority (optional)"},
    ],
    "wordpress": [
        {"path": "/wp-admin", "reason": "WordPress admin dashboard — no SEO value"},
        {"path": "/wp-includes", "reason": "Core WordPress files — not content"},
        {"path": "/wp-content/plugins", "reason": "Plugin files — not indexable content"},
        {"path": "/wp-content/themes", "reason": "Theme files — not indexable content"},
        {"path": "/wp-login.php", "reason": "Login page — no SEO value"},
        {"path": "/wp-register.php", "reason": "Registration page — no SEO value"},
        {"path": "/xmlrpc.php", "reason": "XML-RPC endpoint — security/performance"},
        {"path": "/author", "reason": "Author archive pages — thin content on single-author sites"},
        {"path": "/tag", "reason": "Tag archives — near-duplicate of categories"},
        {"path": "/trackback", "reason": "Trackback URLs — obsolete, spam vector"},
        {"path": "/comments/feed", "reason": "Comment feeds — duplicate content"},
        {"path": "/wp-json", "reason": "REST API — not for search indexing"},
    ],
    "custom": [
        {"path": "/admin", "reason": "Admin panel — no SEO value"},
        {"path": "/login", "reason": "Login page — no SEO value"},
        {"path": "/register", "reason": "Registration page — no SEO value"},
        {"path": "/api", "reason": "API endpoints — not indexable content"},
        {"path": "/search", "reason": "Internal search results — thin content"},
        {"path": "/cart", "reason": "Cart — dynamic, no SEO value"},
        {"path": "/checkout", "reason": "Checkout — private user data"},
    ],
}

# Important pages that should NEVER be blocked
CRITICAL_PATHS = [
    "/", "/about", "/contact", "/blog", "/products", "/services",
    "/sitemap.xml", "/robots.txt", "/privacy-policy", "/terms",
]

# ─── Generator ───

def generate_robots_txt(website_id: int) -> Dict[str, Any]:
    """Generate optimized robots.txt content for a website."""
    db = SessionLocal()
    try:
        website = db.query(Website).filter(Website.id == website_id).first()
        if not website:
            return {"error": "Website not found"}

        domain = website.domain.replace("http://", "").replace("https://", "").rstrip("/")
        base_url = f"https://{domain}"
        site_type = (website.site_type or "custom").lower()

        lines: List[str] = []
        lines.append("# ═══════════════════════════════════════════════════════════════")
        lines.append(f"# robots.txt for {domain}")
        lines.append(f"# Generated by SEO Intelligence Platform")
        lines.append(f"# Site Type: {site_type.title()}")
        lines.append(f"# Generated at: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
        lines.append("# ═══════════════════════════════════════════════════════════════")
        lines.append("")

        # User-agent: *
        lines.append("# ─── Global Crawler Rules ───")
        lines.append("User-agent: *")
        lines.append("")

        # Allow root explicitly
        lines.append("# Allow everything by default, then selectively disallow")
        lines.append("Allow: /")
        lines.append("")

        # Platform-specific disallow rules
        rules = PLATFORM_RULES.get(site_type, PLATFORM_RULES["custom"])
        lines.append(f"# ─── Disallowed Paths ({site_type.title()}-specific) ───")
        for rule in rules:
            lines.append(f"# {rule['reason']}")
            lines.append(f"Disallow: {rule['path']}")
        lines.append("")

        # Common disallows for all sites
        lines.append("# ─── Common Disallows (All Sites) ───")
        lines.append("# Hidden files and directories")
        lines.append("Disallow: /.")
        lines.append("Disallow: /*?*")  # URL parameters — major duplicate content source
        lines.append("Disallow: /*&*")  # Additional parameter separator
        lines.append("")

        # Crawl-delay
        lines.append("# ─── Crawl Rate Limiting ───")
        lines.append("# Be polite to smaller hosts; Google ignores this but Bing/Yahoo respect it")
        lines.append("Crawl-delay: 1")
        lines.append("")

        # Sitemap directive
        lines.append("# ─── Sitemap Location ───")
        sitemap_url = ""
        if website.sitemap_xml:
            sitemap_url = f"{base_url}/sitemap.xml"
            lines.append(f"# Link to generated sitemap ({website.sitemap_generated_at.strftime('%Y-%m-%d') if website.sitemap_generated_at else 'recent'})")
            lines.append(f"Sitemap: {sitemap_url}")
        else:
            lines.append(f"# No sitemap generated yet — generate one in the Sitemap tab")
            lines.append(f"# Sitemap: {base_url}/sitemap.xml")
        lines.append("")

        # Additional user-agents
        lines.append("# ─── Specific Crawler Rules ───")
        lines.append("# Googlebot gets full access (respects Allow/Disallow above)")
        lines.append("User-agent: Googlebot")
        lines.append("Allow: /")
        lines.append("")
        lines.append("# Bingbot — same rules, crawl-delay respected")
        lines.append("User-agent: Bingbot")
        lines.append("Allow: /")
        lines.append("")
        lines.append("# Block aggressive scrapers (optional hard block)")
        lines.append("User-agent: AhrefsBot")
        lines.append("Crawl-delay: 2")
        lines.append("")
        lines.append("User-agent: SemrushBot")
        lines.append("Crawl-delay: 2")
        lines.append("")

        robots_content = "\n".join(lines)

        # Store in DB
        website.robots_txt = robots_content
        db.commit()

        print(f"[Robots] Generated robots.txt for {domain} ({site_type})")

        return {
            "success": True,
            "domain": domain,
            "site_type": site_type,
            "generated_at": datetime.utcnow().isoformat(),
            "robots_txt": robots_content,
            "rule_count": len(rules),
            "sitemap_linked": bool(website.sitemap_xml),
        }

    except Exception as e:
        print(f"[Robots] Generation error: {e}")
        import traceback
        traceback.print_exc()
        return {"error": str(e)}
    finally:
        db.close()


# ─── Validator ───

def validate_robots_txt(robots_content: str, website_id: int) -> Dict[str, Any]:
    """Validate robots.txt content and return warnings/errors."""
    db = SessionLocal()
    try:
        website = db.query(Website).filter(Website.id == website_id).first()
        domain = website.domain if website else "unknown"
        site_type = (website.site_type or "custom").lower() if website else "custom"

        errors: List[str] = []
        warnings: List[str] = []
        info: List[str] = []

        if not robots_content or not robots_content.strip():
            errors.append("robots.txt is empty")
            return {"valid": False, "errors": errors, "warnings": warnings, "info": info}

        lines = robots_content.splitlines()
        has_user_agent = False
        has_sitemap = False
        has_disallow_all = False
        has_crawl_delay = False
        sitemap_urls: List[str] = []
        parsed_rules: List[Dict[str, Any]] = []
        current_agent = "*"

        for line_no, raw_line in enumerate(lines, 1):
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue

            if ":" not in line:
                warnings.append(f"Line {line_no}: Missing colon — '{raw_line.strip()}' may be malformed")
                continue

            key, val = line.split(":", 1)
            key = key.strip().lower()
            val = val.strip()

            if key == "user-agent":
                has_user_agent = True
                current_agent = val
            elif key == "disallow":
                parsed_rules.append({"agent": current_agent, "type": "disallow", "path": val, "line": line_no})
                if val == "/" or val == "":
                    has_disallow_all = True
                    warnings.append(f"Line {line_no}: Disallow: / blocks ALL crawlers for agent '{current_agent}'")
            elif key == "allow":
                parsed_rules.append({"agent": current_agent, "type": "allow", "path": val, "line": line_no})
            elif key == "sitemap":
                has_sitemap = True
                sitemap_urls.append(val)
                if not val.startswith("http"):
                    warnings.append(f"Line {line_no}: Sitemap URL should be absolute (https://...)")
            elif key == "crawl-delay":
                has_crawl_delay = True
                try:
                    delay = float(val)
                    if delay > 10:
                        warnings.append(f"Line {line_no}: Crawl-delay {delay}s is very high — may limit indexing")
                    if delay < 0:
                        errors.append(f"Line {line_no}: Crawl-delay cannot be negative")
                except ValueError:
                    errors.append(f"Line {line_no}: Crawl-delay must be a number")
            elif key not in ("user-agent", "disallow", "allow", "sitemap", "crawl-delay", "host"):
                warnings.append(f"Line {line_no}: Unknown directive '{key}'")

        # Critical checks
        if not has_user_agent:
            errors.append("No User-agent directive found — crawlers won't know which rules apply")

        if not has_sitemap:
            warnings.append("No Sitemap directive found — search engines may miss pages")

        if has_disallow_all:
            errors.append("Disallow: / detected — this blocks ALL search engine crawlers from the entire site")

        # Check if critical pages are blocked
        blocked_critical: List[str] = []
        for rule in parsed_rules:
            if rule["type"] != "disallow" or rule["agent"] not in ("*", "Googlebot", "Bingbot"):
                continue
            path = rule["path"]
            for critical in CRITICAL_PATHS:
                if path == "/":
                    continue
                if critical.startswith(path) or path == critical:
                    blocked_critical.append(f"'{critical}' blocked by '{path}' (line {rule['line']})")

        for bc in blocked_critical:
            warnings.append(f"Critical page potentially blocked: {bc}")

        # Platform-specific checks
        expected_rules = PLATFORM_RULES.get(site_type, PLATFORM_RULES["custom"])
        expected_paths = {r["path"] for r in expected_rules}
        found_disallows = {r["path"] for r in parsed_rules if r["type"] == "disallow"}

        missing = expected_paths - found_disallows
        for m in missing:
            info.append(f"Recommended disallow missing: {m}")

        # Check for common syntax issues
        if "Disallow:" in robots_content and "Disallow: " not in robots_content.replace("Disallow: ", ""):
            # Empty disallow values are actually "allow all" but often confusing
            pass

        # Check for BOM or weird encoding markers
        if robots_content.startswith("\ufeff"):
            warnings.append("File starts with BOM (Byte Order Mark) — may cause parsing issues")

        valid = len(errors) == 0

        print(f"[Robots] Validated robots.txt for {domain}: {len(errors)} errors, {len(warnings)} warnings")

        return {
            "valid": valid,
            "errors": errors,
            "warnings": warnings,
            "info": info,
            "has_sitemap": has_sitemap,
            "has_crawl_delay": has_crawl_delay,
            "sitemap_urls": sitemap_urls,
            "rule_count": len(parsed_rules),
            "blocked_critical": blocked_critical,
        }

    except Exception as e:
        print(f"[Robots] Validation error: {e}")
        return {"valid": False, "errors": [str(e)], "warnings": [], "info": []}
    finally:
        db.close()


# ─── Live Site Checker ───

async def check_existing_robots(website_id: int) -> Dict[str, Any]:
    """Fetch and analyze the current robots.txt from the live website."""
    db = SessionLocal()
    try:
        website = db.query(Website).filter(Website.id == website_id).first()
        if not website:
            return {"error": "Website not found"}

        domain = website.domain.replace("http://", "").replace("https://", "").rstrip("/")
        base_url = f"https://{domain}"
        robots_url = f"{base_url}/robots.txt"

        print(f"[Robots] Fetching existing robots.txt from {robots_url}")

        try:
            async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:
                resp = await client.get(robots_url, headers=DEFAULT_HEADERS)
        except Exception as e:
            return {
                "found": False,
                "error": f"Could not fetch robots.txt: {e}",
                "url": robots_url,
            }

        if resp.status_code == 404:
            return {
                "found": False,
                "error": "robots.txt not found (HTTP 404)",
                "url": robots_url,
                "recommendation": "Create a robots.txt file at the root of your domain",
            }

        if resp.status_code != 200:
            return {
                "found": False,
                "error": f"robots.txt returned HTTP {resp.status_code}",
                "url": robots_url,
            }

        content = resp.text
        content_type = resp.headers.get("content-type", "")

        warnings: List[str] = []
        if "text/plain" not in content_type and "text/html" not in content_type:
            warnings.append(f"Content-Type is '{content_type}' — should be 'text/plain'")

        # Run validation
        validation = validate_robots_txt(content, website_id)

        # Compare with generated
        generated = website.robots_txt or ""
        comparison = _compare_robots(content, generated)

        print(f"[Robots] Fetched existing robots.txt for {domain}: {len(content)} chars")

        return {
            "found": True,
            "url": robots_url,
            "content": content,
            "content_length": len(content),
            "content_type": content_type,
            "validation": validation,
            "comparison": comparison,
            "warnings": warnings,
        }

    except Exception as e:
        print(f"[Robots] Check existing error: {e}")
        return {"error": str(e)}
    finally:
        db.close()


def _compare_robots(existing: str, generated: str) -> Dict[str, Any]:
    """Compare existing vs generated robots.txt and highlight differences."""
    if not generated:
        return {
            "has_generated": False,
            "message": "No generated robots.txt available. Generate one first.",
        }

    # Extract disallow rules from both
    def _extract_rules(text: str) -> set:
        rules = set()
        current_agent = "*"
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if ":" not in line:
                continue
            key, val = line.split(":", 1)
            key = key.strip().lower()
            val = val.strip()
            if key == "user-agent":
                current_agent = val
            elif key in ("disallow", "allow"):
                rules.add((current_agent, key, val))
        return rules

    existing_rules = _extract_rules(existing)
    generated_rules = _extract_rules(generated)

    only_in_existing = existing_rules - generated_rules
    only_in_generated = generated_rules - existing_rules
    in_both = existing_rules & generated_rules

    return {
        "has_generated": True,
        "existing_rule_count": len(existing_rules),
        "generated_rule_count": len(generated_rules),
        "shared_rule_count": len(in_both),
        "only_in_existing": [{"agent": a, "type": t, "path": p} for a, t, p in sorted(only_in_existing)],
        "only_in_generated": [{"agent": a, "type": t, "path": p} for a, t, p in sorted(only_in_generated)],
        "recommendation": (
            "Generated version has additional recommended rules" if only_in_generated else
            "Existing version matches generated version" if not only_in_existing else
            "Review differences before applying generated version"
        ),
    }


# ─── Get stored robots.txt ───

def get_robots_txt(website_id: int) -> Dict[str, Any]:
    """Get the stored robots.txt for a website."""
    db = SessionLocal()
    try:
        website = db.query(Website).filter(Website.id == website_id).first()
        if not website:
            return {"error": "Website not found"}

        if not website.robots_txt:
            return {
                "exists": False,
                "message": "No robots.txt generated yet. Click Generate to create one.",
                "domain": website.domain,
            }

        validation = validate_robots_txt(website.robots_txt, website_id)

        return {
            "exists": True,
            "domain": website.domain,
            "site_type": website.site_type,
            "generated_at": website.robots_txt,  # We don't store generated_at separately; could parse from content
            "robots_txt": website.robots_txt,
            "valid": validation["valid"],
            "validation": validation,
        }
    except Exception as e:
        return {"error": str(e)}
    finally:
        db.close()


# ─── Update robots.txt (from frontend edit) ───

def update_robots_txt(website_id: int, content: str) -> Dict[str, Any]:
    """Update the stored robots.txt with user-edited content."""
    db = SessionLocal()
    try:
        website = db.query(Website).filter(Website.id == website_id).first()
        if not website:
            return {"error": "Website not found"}

        website.robots_txt = content
        db.commit()

        validation = validate_robots_txt(content, website_id)

        print(f"[Robots] Updated robots.txt for {website.domain}")

        return {
            "success": True,
            "valid": validation["valid"],
            "validation": validation,
            "robots_txt": content,
        }
    except Exception as e:
        return {"error": str(e)}
    finally:
        db.close()
